repeat wait() until game:IsLoaded()
repeat wait() until game:GetService("Players").LocalPlayer:WaitForChild('Loaded').Value == true

if workspace:FindFirstChild('Falling Leaves') then
while true do
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "Raid",
    [2] = "Frozen Fields",
    [3] = false
}

game:GetService("ReplicatedStorage").Events.raidEvent:FireServer(unpack(args))
wait()
end

else do

repeat wait() until
game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(6.959071636199951, 160.677978515625, -48.03858184814453)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.Anchored = true
repeat wait()
local args = {
    [1] = "Skill",
    [2] = "Skill3",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
wait(1.8)
local args = {
    [1] = "Skill",
    [2] = "Skill1",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
local args = {
    [1] = "Skill",
    [2] = "Skill2",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
wait(0.1)

local args = {
    [1] = "Skill",
    [2] = "Skill3",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
wait(1.5)
local args = {
    [1] = "Skill",
    [2] = "Skill3",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
until game:GetService("Workspace"):WaitForChild('Mobs'):FindFirstChild("Santa's Elf")

local elf =game:GetService("Workspace"):WaitForChild('Mobs'):FindFirstChild("Santa's Elf")

game.Players.LocalPlayer.Character:WaitForChild('HumanoidRootPart').CFrame = elf.HumanoidRootPart.CFrame + Vector3.new(0,0,0)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.Anchored = false
wait(0.1)
for i = 1, 2 do
game.Players.LocalPlayer.Character.HumanoidRootPart.Anchored = true

local args = {
    [1] = "Skill",
    [2] = "Skill3",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
wait(1.8)
local args = {
    [1] = "Skill",
    [2] = "Skill1",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
local args = {
    [1] = "Skill",
    [2] = "Skill2",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
wait(0.1)

local args = {
    [1] = "Skill",
    [2] = "Skill3",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
wait(1.5)
local args = {
    [1] = "Skill",
    [2] = "Skill3",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
end
game.Players.LocalPlayer.Character.HumanoidRootPart.Anchored = false
game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(6.959071636199951, 160.677978515625, -48.03858184814453)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.Anchored = true
repeat wait()
local args = {
    [1] = "Skill",
    [2] = "Skill3",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
wait(1.8)
local args = {
    [1] = "Skill",
    [2] = "Skill1",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
local args = {
    [1] = "Skill",
    [2] = "Skill2",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
wait(0.1)

local args = {
    [1] = "Skill",
    [2] = "Skill3",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
wait(1.5)
local args = {
    [1] = "Skill",
    [2] = "Skill3",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
until game:GetService("Workspace"):WaitForChild('Mobs'):FindFirstChild("Jack Frost")

local Frost =game:GetService("Workspace"):WaitForChild('Mobs'):FindFirstChild("Jack Frost")

game.Players.LocalPlayer.Character:WaitForChild('HumanoidRootPart').CFrame = Frost.HumanoidRootPart.CFrame + Vector3.new(0,0,0)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.Anchored = false
wait(0.1)
for i = 1, 3 do
game.Players.LocalPlayer.Character.HumanoidRootPart.Anchored = true

local args = {
    [1] = "Skill",
    [2] = "Skill3",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
wait(1.8)
local args = {
    [1] = "Skill",
    [2] = "Skill1",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
local args = {
    [1] = "Skill",
    [2] = "Skill2",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
wait(0.1)

local args = {
    [1] = "Skill",
    [2] = "Skill3",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
wait(1.5)
local args = {
    [1] = "Skill",
    [2] = "Skill3",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
end
game.Players.LocalPlayer.Character.HumanoidRootPart.Anchored = false
game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(6.959071636199951, 160.677978515625, -48.03858184814453)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.Anchored = true
repeat wait()
local args = {
    [1] = "Skill",
    [2] = "Skill3",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
wait(1.8)
local args = {
    [1] = "Skill",
    [2] = "Skill1",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
local args = {
    [1] = "Skill",
    [2] = "Skill2",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
wait(0.1)

local args = {
    [1] = "Skill",
    [2] = "Skill3",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
wait(1.5)
local args = {
    [1] = "Skill",
    [2] = "Skill3",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
until game:GetService("Workspace"):WaitForChild('Mobs'):FindFirstChild("The Last Reindeer")

local viado =game:GetService("Workspace"):WaitForChild('Mobs'):FindFirstChild("The Last Reindeer ")

game.Players.LocalPlayer.Character:WaitForChild('HumanoidRootPart').CFrame = viado.HumanoidRootPart.CFrame + Vector3.new(0,0,0)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.Anchored = false
wait(0.1)
for i = 1, 4 do
game.Players.LocalPlayer.Character.HumanoidRootPart.Anchored = true

local args = {
    [1] = "Skill",
    [2] = "Skill3",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
wait(1.8)
local args = {
    [1] = "Skill",
    [2] = "Skill1",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
local args = {
    [1] = "Skill",
    [2] = "Skill2",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
wait(0.1)

local args = {
    [1] = "Skill",
    [2] = "Skill3",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
wait(1.5)
local args = {
    [1] = "Skill",
    [2] = "Skill3",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
end
game.Players.LocalPlayer.Character.HumanoidRootPart.Anchored = false
game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(6.959071636199951, 160.677978515625, -48.03858184814453)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.Anchored = true
repeat wait()
local args = {
    [1] = "Skill",
    [2] = "Skill3",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
wait(1.8)
local args = {
    [1] = "Skill",
    [2] = "Skill1",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
local args = {
    [1] = "Skill",
    [2] = "Skill2",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
wait(0.1)

local args = {
    [1] = "Skill",
    [2] = "Skill3",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
wait(1.5)
local args = {
    [1] = "Skill",
    [2] = "Skill3",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
until game:GetService("Workspace"):WaitForChild('Mobs'):FindFirstChild("Moon")

local Moon =game:GetService("Workspace"):WaitForChild('Mobs'):FindFirstChild("Moon")

game.Players.LocalPlayer.Character:WaitForChild('HumanoidRootPart').CFrame = Moon.HumanoidRootPart.CFrame + Vector3.new(0,0,0)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.Anchored = false
wait(0.1)
for i = 1, 6 do
game.Players.LocalPlayer.Character.HumanoidRootPart.Anchored = true

local args = {
    [1] = "Skill",
    [2] = "Skill3",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
wait(1.8)
local args = {
    [1] = "Skill",
    [2] = "Skill1",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
local args = {
    [1] = "Skill",
    [2] = "Skill2",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
wait(0.1)

local args = {
    [1] = "Skill",
    [2] = "Skill3",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
wait(1.5)
local args = {
    [1] = "Skill",
    [2] = "Skill3",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
end
game.Players.LocalPlayer.Character.HumanoidRootPart.Anchored = false
game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(6.959071636199951, 160.677978515625, -48.03858184814453)
wait(0.1)
game.Players.LocalPlayer.Character.HumanoidRootPart.Anchored = true
repeat wait()
local args = {
    [1] = "Skill",
    [2] = "Skill3",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
wait(1.8)
local args = {
    [1] = "Skill",
    [2] = "Skill1",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
local args = {
    [1] = "Skill",
    [2] = "Skill2",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
wait(0.1)

local args = {
    [1] = "Skill",
    [2] = "Skill3",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
wait(1.5)
local args = {
    [1] = "Skill",
    [2] = "Skill3",
    [3] = "Attack"
}

game:GetService("ReplicatedStorage"):WaitForChild("Events"):WaitForChild("attack"):FireServer(unpack(args))
until game:GetService("Workspace"):WaitForChild('Mobs'):FindFirstChild("Jack Frost")
end
end
